### ISSUE TITLE
Don't commit minified files if there are no changes to non-minified versions

### ISSUE THREAD

**Issue by boonebgorges** [buddypress/bp-sync-to-wporg#2]
Running the build process results in js/css files being reminimized. When this happens, new timestamp headers are generated, which is enough to make the file "different" from SVN's point of view. This makes the changesets pushed to plugins.svn.wordpress.org unnecessarily big; they'd be easier to scan if they didn't include these unnecessary files. It'd be nice if there were logic that identified whether a non-minified asset had been changed, and discarded the changes to the minified file (`svn revert`, I guess) if there are no actual changes.

**Comment by ntwb** [comment]
I'd suggest removing the timestamps, I removed the timestamps from bbPress for this reason which stemmed from the discussion in [#30666](https://core.trac.wordpress.org/ticket/30666#comment:6)

https://bbpress.trac.wordpress.org/changeset/5912

**Comment by ntwb** [comment]
Also https://buddypress.trac.wordpress.org/ticket/6541

**Comment by paulgibbs** [comment]
Fixed in https://buddypress.trac.wordpress.org/changeset/10705
